export const diablo2ioMapping: {[itemName: string]: string} = {
  "Aldur's Advance": "https://diablo2.io/sets/aldur-s-advance-t1037.html",
  "Aldur's Deception": "https://diablo2.io/sets/aldur-s-deception-t1036.html",
  "Aldur's Rhythm": "https://diablo2.io/sets/aldur-s-rhythm-t1034.html",
  "Aldur's Stony Gaze": "https://diablo2.io/sets/aldur-s-stony-gaze-t1035.html",
  "Aldur's Watchtower": "https://diablo2.io/sets/aldur-s-watchtower-t1033.html",
  "Alma Negra": "https://diablo2.io/uniques/alma-negra-t668.html",
  "Andariel's Visage": "https://diablo2.io/uniques/andariel-s-visage-t669.html",
  "Angelic Halo": "https://diablo2.io/sets/angelic-halo-t1040.html",
  "Angelic Mantle": "https://diablo2.io/sets/angelic-mantle-t1041.html",
  "Angelic Raiment": "https://diablo2.io/sets/angelic-raiment-t1038.html",
  "Angelic Sickle": "https://diablo2.io/sets/angelic-sickle-t1042.html",
  "Angelic Wings": "https://diablo2.io/sets/angelic-wings-t1039.html",
  "Annihilus": "https://diablo2.io/uniques/annihilus-t670.html",
  "Arachnid Mesh": "https://diablo2.io/uniques/arachnid-mesh-t671.html",
  "Arcanna's Deathwand": "https://diablo2.io/sets/arcanna-s-deathwand-t1047.html",
  "Arcanna's Flesh": "https://diablo2.io/sets/arcanna-s-flesh-t1046.html",
  "Arcanna's Head": "https://diablo2.io/sets/arcanna-s-head-t1045.html",
  "Arcanna's Sign": "https://diablo2.io/sets/arcanna-s-sign-t1044.html",
  "Arcanna's Tricks": "https://diablo2.io/sets/arcanna-s-tricks-t1043.html",
  "Arctic Binding": "https://diablo2.io/sets/arctic-binding-t1050.html",
  "Arctic Furs": "https://diablo2.io/sets/arctic-furs-t1051.html",
  "Arctic Gear": "https://diablo2.io/sets/arctic-gear-t1048.html",
  "Arctic Horn": "https://diablo2.io/sets/arctic-horn-t1052.html",
  "Arctic Mitts": "https://diablo2.io/sets/arctic-mitts-t1049.html",
  "Arioc's Needle": "https://diablo2.io/uniques/arioc-s-needle-t672.html",
  "Arkaine's Valor": "https://diablo2.io/uniques/arkaine-s-valor-t673.html",
  "Arm of King Leoric": "https://diablo2.io/uniques/arm-of-king-leoric-t674.html",
  "Arreat's Face": "https://diablo2.io/uniques/arreat-s-face-t675.html",
  "Astreon's Iron Ward": "https://diablo2.io/uniques/astreon-s-iron-ward-t676.html",
  "Athena's Wrath": "https://diablo2.io/uniques/athena-s-wrath-t677.html",
  "Atma's Scarab": "https://diablo2.io/uniques/atma-s-scarab-t678.html",
  "Atma's Wail": "https://diablo2.io/uniques/atma-s-wail-t679.html",
  "Axe of Fechmar": "https://diablo2.io/uniques/axe-of-fechmar-t680.html",
  "Azurewrath": "https://diablo2.io/uniques/azurewrath-t681.html",
  "Baezil's Vortex": "https://diablo2.io/uniques/baezil-s-vortex-t682.html",
  "Bane Ash": "https://diablo2.io/uniques/bane-ash-t683.html",
  "Baranar's Star": "https://diablo2.io/uniques/baranar-s-star-t684.html",
  "Bartuc's Cut-Throat": "https://diablo2.io/uniques/bartuc-s-cut-throat-t685.html",
  "Berserker's Arsenal": "https://diablo2.io/sets/berserker-s-arsenal-t1053.html",
  "Berserker's Hatchet": "https://diablo2.io/sets/berserker-s-hatchet-t1054.html",
  "Berserker's Hauberk": "https://diablo2.io/sets/berserker-s-hauberk-t1055.html",
  "Berserker's Headgear": "https://diablo2.io/sets/berserker-s-headgear-t1056.html",
  "Biggin's Bonnet": "https://diablo2.io/uniques/biggin-s-bonnet-t686.html",
  "Bing Sz Wang": "https://diablo2.io/uniques/bing-sz-wang-t687.html",
  "Black Hades": "https://diablo2.io/uniques/black-hades-t688.html",
  "Blackbog's Sharp": "https://diablo2.io/uniques/blackbog-s-sharp-t689.html",
  "Blackhand Key": "https://diablo2.io/uniques/blackhand-key-t690.html",
  "Blackhorn's Face": "https://diablo2.io/uniques/blackhorn-s-face-t691.html",
  "Blackleach Blade": "https://diablo2.io/uniques/blackleach-blade-t692.html",
  "Blackoak Shield": "https://diablo2.io/uniques/blackoak-shield-t693.html",
  "Blacktongue": "https://diablo2.io/uniques/blacktongue-t694.html",
  "Blade of Ali Baba": "https://diablo2.io/uniques/blade-of-ali-baba-t695.html",
  "Bladebone": "https://diablo2.io/uniques/bladebone-t696.html",
  "Bladebuckle": "https://diablo2.io/uniques/bladebuckle-t697.html",
  "Blastbark": "https://diablo2.io/uniques/blastbark-t698.html",
  "Blinkbat's Form": "https://diablo2.io/uniques/blinkbat-s-form-t699.html",
  "Blood Crescent": "https://diablo2.io/uniques/blood-crescent-t700.html",
  "Blood Raven's Charge": "https://diablo2.io/uniques/blood-raven-s-charge-t701.html",
  "Bloodfist": "https://diablo2.io/uniques/bloodfist-t702.html",
  "Bloodletter": "https://diablo2.io/uniques/bloodletter-t703.html",
  "Bloodmoon": "https://diablo2.io/uniques/bloodmoon-t704.html",
  "Bloodrise": "https://diablo2.io/uniques/bloodrise-t705.html",
  "Bloodthief": "https://diablo2.io/uniques/bloodthief-t706.html",
  "Bloodtree Stump": "https://diablo2.io/uniques/bloodtree-stump-t707.html",
  "Boneflame": "https://diablo2.io/uniques/boneflame-t708.html",
  "Boneflesh": "https://diablo2.io/uniques/boneflesh-t709.html",
  "Bonehew": "https://diablo2.io/uniques/bonehew-t710.html",
  "Boneshade": "https://diablo2.io/uniques/boneshade-t711.html",
  "Boneslayer Blade": "https://diablo2.io/uniques/boneslayer-blade-t712.html",
  "Bonesnap": "https://diablo2.io/uniques/bonesnap-t713.html",
  "Brainhew": "https://diablo2.io/uniques/brainhew-t714.html",
  "Bul-Kathos' Children": "https://diablo2.io/sets/bul-kathos-children-t1057.html",
  "Bul-Kathos' Sacred Charge": "https://diablo2.io/sets/bul-kathos-sacred-charge-t1058.html",
  "Bul-Kathos' Tribal Guardian": "https://diablo2.io/sets/bul-kathos-tribal-guardian-t1059.html",
  "Bul-Kathos' Wedding Band": "https://diablo2.io/uniques/bul-kathos-wedding-band-t715.html",
  "Buriza-Do Kyanon": "https://diablo2.io/uniques/buriza-do-kyanon-t716.html",
  "Butcher's Pupil": "https://diablo2.io/uniques/butcher-s-pupil-t717.html",
  "Bverrit Keep": "https://diablo2.io/uniques/bverrit-keep-t718.html",
  "Carin Shard": "https://diablo2.io/uniques/carin-shard-t719.html",
  "Carrion Wind": "https://diablo2.io/uniques/carrion-wind-t720.html",
  "Cathan's Mesh": "https://diablo2.io/sets/cathan-s-mesh-t33.html",
  "Cathan's Rule": "https://diablo2.io/sets/cathan-s-rule-t30.html",
  "Cathan's Seal": "https://diablo2.io/sets/cathan-s-seal-t31.html",
  "Cathan's Sigil": "https://diablo2.io/sets/cathan-s-sigil-t32.html",
  "Cathan's Traps": "https://diablo2.io/sets/cathan-s-traps-t29.html",
  "Cathan's Visage": "https://diablo2.io/sets/cathan-s-visage-t4.html",
  "Cerebus' Bite": "https://diablo2.io/uniques/cerebus-bite-t721.html",
  "Chance Guards": "https://diablo2.io/uniques/chance-guards-t722.html",
  "Chromatic Ire": "https://diablo2.io/uniques/chromatic-ire-t723.html",
  "Civerb's Cudgel": "https://diablo2.io/sets/civerb-s-cudgel-t1061.html",
  "Civerb's Icon": "https://diablo2.io/sets/civerb-s-icon-t1063.html",
  "Civerb's Vestments": "https://diablo2.io/sets/civerb-s-vestments-t1060.html",
  "Civerb's Ward": "https://diablo2.io/sets/civerb-s-ward-t1062.html",
  "Cleglaw's Brace": "https://diablo2.io/sets/cleglaw-s-brace-t1064.html",
  "Cleglaw's Claw": "https://diablo2.io/sets/cleglaw-s-claw-t1066.html",
  "Cleglaw's Pincers": "https://diablo2.io/sets/cleglaw-s-pincers-t1067.html",
  "Cleglaw's Tooth": "https://diablo2.io/sets/cleglaw-s-tooth-t1065.html",
  "Cliffkiller": "https://diablo2.io/uniques/cliffkiller-t724.html",
  "Cloudcrack": "https://diablo2.io/uniques/cloudcrack-t725.html",
  "Coif of Glory": "https://diablo2.io/uniques/coif-of-glory-t726.html",
  "Coldkill": "https://diablo2.io/uniques/coldkill-t727.html",
  "Coldsteel Eye": "https://diablo2.io/uniques/coldsteel-eye-t728.html",
  "Corpsemourn": "https://diablo2.io/uniques/corpsemourn-t729.html",
  "Cow King's Hide": "https://diablo2.io/sets/cow-king-s-hide-t1070.html",
  "Cow King's Hooves": "https://diablo2.io/sets/cow-king-s-hooves-t1071.html",
  "Cow King's Horns": "https://diablo2.io/sets/cow-king-s-horns-t1069.html",
  "Cow King's Leathers": "https://diablo2.io/sets/cow-king-s-leathers-t1068.html",
  "Crainte Vomir": "https://diablo2.io/uniques/crainte-vomir-t730.html",
  "Cranebeak": "https://diablo2.io/uniques/cranebeak-t731.html",
  "Credendum": "https://diablo2.io/sets/credendum-t1167.html",
  "Crescent Moon": "https://diablo2.io/uniques/crescent-moon-amulet-t732.html",
  "Crow Caw": "https://diablo2.io/uniques/crow-caw-t733.html",
  "Crown of Ages": "https://diablo2.io/uniques/crown-of-ages-t734.html",
  "Crown of Thieves": "https://diablo2.io/uniques/crown-of-thieves-t735.html",
  "Crushflange": "https://diablo2.io/uniques/crushflange-t736.html",
  "Culwen's Point": "https://diablo2.io/uniques/culwen-s-point-t737.html",
  "Dangoon's Teaching": "https://diablo2.io/sets/dangoon-s-teaching-t1082.html",
  "Dark Adherent": "https://diablo2.io/sets/dark-adherent-t1166.html",
  "Dark Clan Crusher": "https://diablo2.io/uniques/dark-clan-crusher-t738.html",
  "Darkforce Spawn": "https://diablo2.io/uniques/darkforce-spawn-t739.html",
  "Darkglow": "https://diablo2.io/uniques/darkglow-t740.html",
  "Darksight Helm": "https://diablo2.io/uniques/darksight-helm-t741.html",
  "Death Cleaver": "https://diablo2.io/uniques/death-cleaver-t742.html",
  "Death's Disguise": "https://diablo2.io/sets/death-s-disguise-t1072.html",
  "Death's Fathom": "https://diablo2.io/uniques/death-s-fathom-t744.html",
  "Death's Guard": "https://diablo2.io/sets/death-s-guard-t1074.html",
  "Death's Hand": "https://diablo2.io/sets/death-s-hand-t1075.html",
  "Death's Touch": "https://diablo2.io/sets/death-s-touch-t1073.html",
  "Death's Web": "https://diablo2.io/uniques/death-s-web-t745.html",
  "Deathbit": "https://diablo2.io/uniques/deathbit-t743.html",
  "Deathspade": "https://diablo2.io/uniques/deathspade-t746.html",
  "Demon Limb": "https://diablo2.io/uniques/demon-limb-t747.html",
  "Demon Machine": "https://diablo2.io/uniques/demon-machine-t748.html",
  "Demon's Arch": "https://diablo2.io/uniques/demon-s-arch-t750.html",
  "Demonhorn's Edge": "https://diablo2.io/uniques/demonhorn-s-edge-t749.html",
  "Dimoak's Hew": "https://diablo2.io/uniques/dimoak-s-hew-t751.html",
  "Djinn Slayer": "https://diablo2.io/uniques/djinn-slayer-t752.html",
  "Doombringer": "https://diablo2.io/uniques/doombringer-t753.html",
  "Doomslinger": "https://diablo2.io/uniques/doomslinger-t754.html",
  "Dracul's Grasp": "https://diablo2.io/uniques/dracul-s-grasp-t755.html",
  "Dragonscale": "https://diablo2.io/uniques/dragonscale-t756.html",
  "Duriel's Shell": "https://diablo2.io/uniques/duriel-s-shell-t757.html",
  "Duskdeep": "https://diablo2.io/uniques/duskdeep-t758.html",
  "Dwarf Star": "https://diablo2.io/uniques/dwarf-star-t759.html",
  "Eaglehorn": "https://diablo2.io/uniques/eaglehorn-t760.html",
  "Earth Shifter": "https://diablo2.io/uniques/earth-shifter-t761.html",
  "Earthshaker": "https://diablo2.io/uniques/earthshaker-t762.html",
  "Endlesshail": "https://diablo2.io/uniques/endlesshail-t763.html",
  "Eschuta's Temper": "https://diablo2.io/uniques/eschuta-s-temper-t764.html",
  "Ethereal Edge": "https://diablo2.io/uniques/ethereal-edge-t765.html",
  "Executioner's Justice": "https://diablo2.io/uniques/executioner-s-justice-t766.html",
  "Felloak": "https://diablo2.io/uniques/felloak-t767.html",
  "Firelizard's Talons": "https://diablo2.io/uniques/firelizard-s-talons-t768.html",
  "Flamebellow": "https://diablo2.io/uniques/flamebellow-t769.html",
  "Fleshrender": "https://diablo2.io/uniques/fleshrender-t770.html",
  "Fleshripper": "https://diablo2.io/uniques/fleshripper-t771.html",
  "Frostburn": "https://diablo2.io/uniques/frostburn-t772.html",
  "Frostwind": "https://diablo2.io/uniques/frostwind-t773.html",
  "Gargoyle's Bite": "https://diablo2.io/uniques/gargoyle-s-bite-t774.html",
  "Gerke's Sanctuary": "https://diablo2.io/uniques/gerke-s-sanctuary-t775.html",
  "Gheed's Fortune": "https://diablo2.io/uniques/gheed-s-fortune-t776.html",
  "Ghostflame": "https://diablo2.io/uniques/ghostflame-t777.html",
  "Ghoulhide": "https://diablo2.io/uniques/ghoulhide-t778.html",
  "Giant Skull": "https://diablo2.io/uniques/giant-skull-t779.html",
  "Gimmershred": "https://diablo2.io/uniques/gimmershred-t780.html",
  "Ginther's Rift": "https://diablo2.io/uniques/ginther-s-rift-t781.html",
  "Gleamscythe": "https://diablo2.io/uniques/gleamscythe-t782.html",
  "Gloom's Trap": "https://diablo2.io/uniques/gloom-s-trap-t783.html",
  "Goblin Toe": "https://diablo2.io/uniques/goblin-toe-t784.html",
  "Goldskin": "https://diablo2.io/uniques/goldskin-t785.html",
  "Goldstrike Arch": "https://diablo2.io/uniques/goldstrike-arch-t786.html",
  "Goldwrap": "https://diablo2.io/uniques/goldwrap-t787.html",
  "Gore Rider": "https://diablo2.io/uniques/gore-rider-t788.html",
  "Gorefoot": "https://diablo2.io/uniques/gorefoot-t789.html",
  "Goreshovel": "https://diablo2.io/uniques/goreshovel-t790.html",
  "Gravenspine": "https://diablo2.io/uniques/gravenspine-t791.html",
  "Gravepalm": "https://diablo2.io/uniques/gravepalm-t792.html",
  "Greyform": "https://diablo2.io/uniques/greyform-t793.html",
  "Griffon's Eye": "https://diablo2.io/uniques/griffon-s-eye-t794.html",
  "Grim's Burning Dead": "https://diablo2.io/uniques/grim-s-burning-dead-t795.html",
  "Griswold's Edge": "https://diablo2.io/uniques/griswold-s-edge-t796.html",
  "Griswold's Heart": "https://diablo2.io/sets/griswold-s-heart-t1079.html",
  "Griswold's Honor": "https://diablo2.io/sets/griswold-s-honor-t1080.html",
  "Griswold's Legacy": "https://diablo2.io/sets/griswold-s-legacy-t1076.html",
  "Griswold's Redemption": "https://diablo2.io/sets/griswold-s-redemption-t1077.html",
  "Griswold's Valor": "https://diablo2.io/sets/griswold-s-valor-t1078.html",
  "Guardian Angel": "https://diablo2.io/uniques/guardian-angel-t797.html",
  "Guardian Naga": "https://diablo2.io/uniques/guardian-naga-t798.html",
  "Guillaume's Face": "https://diablo2.io/sets/guillaume-s-face-t1135.html",
  "Gull": "https://diablo2.io/uniques/gull-t799.html",
  "Gut Siphon": "https://diablo2.io/uniques/gut-siphon-t800.html",
  "Haemosu's Adamant": "https://diablo2.io/sets/haemosu-s-adamant-t1083.html",
  "Halaberd's Reign": "https://diablo2.io/uniques/halaberd-s-reign-t801.html",
  "Hand of Blessed Light": "https://diablo2.io/uniques/hand-of-blessed-light-t802.html",
  "Harlequin Crest": "https://diablo2.io/uniques/harlequin-crest-t37.html",
  "Hawkmail": "https://diablo2.io/uniques/hawkmail-t803.html",
  "Head Hunter's Glory": "https://diablo2.io/uniques/head-hunter-s-glory-t804.html",
  "Headstriker": "https://diablo2.io/uniques/headstriker-t805.html",
  "Heart Carver": "https://diablo2.io/uniques/heart-carver-t806.html",
  "Heaven's Brethren": "https://diablo2.io/sets/heaven-s-brethren-t1081.html",
  "Heaven's Light": "https://diablo2.io/uniques/heaven-s-light-t808.html",
  "Heavenly Garb": "https://diablo2.io/uniques/heavenly-garb-t807.html",
  "Hellcast": "https://diablo2.io/uniques/hellcast-t809.html",
  "Hellclap": "https://diablo2.io/uniques/hellclap-t810.html",
  "Hellfire Torch": "https://diablo2.io/uniques/hellfire-torch-t39.html",
  "Hellmouth": "https://diablo2.io/uniques/hellmouth-t811.html",
  "Hellplague": "https://diablo2.io/uniques/hellplague-t812.html",
  "Hellrack": "https://diablo2.io/uniques/hellrack-t813.html",
  "Hellslayer": "https://diablo2.io/uniques/hellslayer-t814.html",
  "Herald of Zakarum": "https://diablo2.io/uniques/herald-of-zakarum-t815.html",
  "Hexfire": "https://diablo2.io/uniques/hexfire-t816.html",
  "Highlord's Wrath": "https://diablo2.io/uniques/highlord-s-wrath-t817.html",
  "Homunculus": "https://diablo2.io/uniques/homunculus-t818.html",
  "Hone Sundan": "https://diablo2.io/uniques/hone-sundan-t819.html",
  "Horizon's Tornado": "https://diablo2.io/uniques/horizon-s-tornado-t820.html",
  "Hotspur": "https://diablo2.io/uniques/hotspur-t821.html",
  "Howltusk": "https://diablo2.io/uniques/howltusk-t822.html",
  "Hsarus' Defense": "https://diablo2.io/sets/hsarus-defense-t1086.html",
  "Hsarus' Iron Fist": "https://diablo2.io/sets/hsarus-iron-fist-t1088.html",
  "Hsarus' Iron Heel": "https://diablo2.io/sets/hsarus-iron-heel-t1089.html",
  "Hsarus' Iron Stay": "https://diablo2.io/sets/hsarus-iron-stay-t1087.html",
  "Humongous": "https://diablo2.io/uniques/humongous-t823.html",
  "Husoldal Evo": "https://diablo2.io/uniques/husoldal-evo-t824.html",
  "Hwanin's Blessing": "https://diablo2.io/sets/hwanin-s-blessing-t1094.html",
  "Hwanin's Justice": "https://diablo2.io/sets/hwanin-s-justice-t1091.html",
  "Hwanin's Majesty": "https://diablo2.io/sets/hwanin-s-majesty-t1090.html",
  "Hwanin's Refuge": "https://diablo2.io/sets/hwanin-s-refuge-t1092.html",
  "Hwanin's Splendor": "https://diablo2.io/sets/hwanin-s-splendor-t1093.html",
  "Iceblink": "https://diablo2.io/uniques/iceblink-t825.html",
  "Ichorsting": "https://diablo2.io/uniques/ichorsting-t826.html",
  "Immortal King's Detail": "https://diablo2.io/sets/immortal-king-s-detail-t59.html",
  "Immortal King's Forge": "https://diablo2.io/sets/immortal-king-s-forge-t1097.html",
  "Immortal King's Pillar": "https://diablo2.io/sets/immortal-king-s-pillar-t1098.html",
  "Immortal King's Soul Cage": "https://diablo2.io/sets/immortal-king-s-soul-cage-t1096.html",
  "Immortal King's Stone Crusher": "https://diablo2.io/sets/immortal-king-s-stone-crusher-t58.html",
  "Immortal King's Will": "https://diablo2.io/sets/immortal-king-s-will-t1095.html",
  "Immortal King": "https://diablo2.io/sets/immortal-king-t91.html",
  "Infernal Cranium": "https://diablo2.io/sets/infernal-cranium-t1102.html",
  "Infernal Sign": "https://diablo2.io/sets/infernal-sign-t1100.html",
  "Infernal Tools": "https://diablo2.io/sets/infernal-tools-t1099.html",
  "Infernal Torch": "https://diablo2.io/sets/infernal-torch-t1101.html",
  "Infernostride": "https://diablo2.io/uniques/infernostride-t827.html",
  "Iratha's Coil": "https://diablo2.io/sets/iratha-s-coil-t1104.html",
  "Iratha's Collar": "https://diablo2.io/sets/iratha-s-collar-t1107.html",
  "Iratha's Cord": "https://diablo2.io/sets/iratha-s-cord-t1106.html",
  "Iratha's Cuff": "https://diablo2.io/sets/iratha-s-cuff-t1105.html",
  "Iratha's Finery": "https://diablo2.io/sets/iratha-s-finery-t1103.html",
  "Iron Pelt": "https://diablo2.io/uniques/iron-pelt-t828.html",
  "Ironstone": "https://diablo2.io/uniques/ironstone-t829.html",
  "Isenhart's Armory": "https://diablo2.io/sets/isenhart-s-armory-t1108.html",
  "Isenhart's Case": "https://diablo2.io/sets/isenhart-s-case-t1110.html",
  "Isenhart's Horns": "https://diablo2.io/sets/isenhart-s-horns-t1111.html",
  "Isenhart's Lightbrand": "https://diablo2.io/sets/isenhart-s-lightbrand-t1109.html",
  "Isenhart's Parry": "https://diablo2.io/sets/isenhart-s-parry-t1112.html",
  "Islestrike": "https://diablo2.io/uniques/islestrike-t830.html",
  "Jade Talon": "https://diablo2.io/uniques/jade-talon-t831.html",
  "Jalal's Mane": "https://diablo2.io/uniques/jalal-s-mane-t832.html",
  "Kelpie Snare": "https://diablo2.io/uniques/kelpie-snare-t833.html",
  "Kinemil's Awl": "https://diablo2.io/uniques/kinemil-s-awl-t834.html",
  "Kira's Guardian": "https://diablo2.io/uniques/kira-s-guardian-t835.html",
  "Knell Striker": "https://diablo2.io/uniques/knell-striker-t836.html",
  "Kuko Shakaku": "https://diablo2.io/uniques/kuko-shakaku-t837.html",
  "Lacerator": "https://diablo2.io/uniques/lacerator-t838.html",
  "Lance Guard": "https://diablo2.io/uniques/lance-guard-t839.html",
  "Lance of Yaggai": "https://diablo2.io/uniques/lance-of-yaggai-t840.html",
  "Langer Briser": "https://diablo2.io/uniques/langer-briser-t841.html",
  "Lava Gout": "https://diablo2.io/uniques/lava-gout-t842.html",
  "Laying of Hands": "https://diablo2.io/sets/laying-of-hands-t1168.html",
  "Leadcrow": "https://diablo2.io/uniques/leadcrow-t843.html",
  "Lenymo": "https://diablo2.io/uniques/lenymo-t844.html",
  "Leviathan": "https://diablo2.io/uniques/leviathan-t845.html",
  "Lidless Wall": "https://diablo2.io/uniques/lidless-wall-t846.html",
  "Lightsabre": "https://diablo2.io/uniques/lightsabre-t847.html",
  "Lycander's Aim": "https://diablo2.io/uniques/lycander-s-aim-t848.html",
  "Lycander's Flank": "https://diablo2.io/uniques/lycander-s-flank-t849.html",
  "M'avina's Battle Hymn": "https://diablo2.io/sets/m-avina-s-battle-hymn-t1113.html",
  "M'avina's Caster": "https://diablo2.io/sets/m-avina-s-caster-t1114.html",
  "M'avina's Embrace": "https://diablo2.io/sets/m-avina-s-embrace-t1115.html",
  "M'avina's Icy Clutch": "https://diablo2.io/sets/m-avina-s-icy-clutch-t1118.html",
  "M'avina's Tenet": "https://diablo2.io/sets/m-avina-s-tenet-t1117.html",
  "M'avina's True Sight": "https://diablo2.io/sets/m-avina-s-true-sight-t1116.html",
  "Maelstrom": "https://diablo2.io/uniques/maelstrom-t850.html",
  "Magefist": "https://diablo2.io/uniques/magefist-t851.html",
  "Magewrath": "https://diablo2.io/uniques/magewrath-t852.html",
  "Magnus' Skin": "https://diablo2.io/sets/magnus-skin-t1137.html",
  "Manald Heal": "https://diablo2.io/uniques/manald-heal-t853.html",
  "Mang Song's Lesson": "https://diablo2.io/uniques/mang-song-s-lesson-t854.html",
  "Mara's Kaleidoscope": "https://diablo2.io/uniques/mara-s-kaleidoscope-t855.html",
  "Marrowwalk": "https://diablo2.io/uniques/marrowwalk-t856.html",
  "Medusa's Gaze": "https://diablo2.io/uniques/medusa-s-gaze-t857.html",
  "Messerschmidt's Reaver": "https://diablo2.io/uniques/messerschmidt-s-reaver-t858.html",
  "Metalgrid": "https://diablo2.io/uniques/metalgrid-t859.html",
  "Milabrega's Diadem": "https://diablo2.io/sets/milabrega-s-diadem-t1122.html",
  "Milabrega's Orb": "https://diablo2.io/sets/milabrega-s-orb-t1123.html",
  "Milabrega's Regalia": "https://diablo2.io/sets/milabrega-s-regalia-t1119.html",
  "Milabrega's Robe": "https://diablo2.io/sets/milabrega-s-robe-t1121.html",
  "Milabrega's Rod": "https://diablo2.io/sets/milabrega-s-rod-t1120.html",
  "Moonfall": "https://diablo2.io/uniques/moonfall-t860.html",
  "Moser's Blessed Circle": "https://diablo2.io/uniques/moser-s-blessed-circle-t861.html",
  "Nagelring": "https://diablo2.io/uniques/nagelring-t862.html",
  "Naj's Ancient Vestige": "https://diablo2.io/sets/naj-s-ancient-vestige-t1124.html",
  "Naj's Circlet": "https://diablo2.io/sets/naj-s-circlet-t1125.html",
  "Naj's Light Plate": "https://diablo2.io/sets/naj-s-light-plate-t1126.html",
  "Naj's Puzzler": "https://diablo2.io/sets/naj-s-puzzler-t1127.html",
  "Natalya's Mark": "https://diablo2.io/sets/natalya-s-mark-t1129.html",
  "Natalya's Odium": "https://diablo2.io/sets/natalya-s-odium-t1128.html",
  "Natalya's Shadow": "https://diablo2.io/sets/natalya-s-shadow-t1130.html",
  "Natalya's Soul": "https://diablo2.io/sets/natalya-s-soul-t1132.html",
  "Natalya's Totem": "https://diablo2.io/sets/natalya-s-totem-t1131.html",
  "Nature's Peace": "https://diablo2.io/uniques/nature-s-peace-t863.html",
  "Nightsmoke": "https://diablo2.io/uniques/nightsmoke-t864.html",
  "Nightwing's Veil": "https://diablo2.io/uniques/nightwing-s-veil-t865.html",
  "Nokozan Relic": "https://diablo2.io/uniques/nokozan-relic-t866.html",
  "Nord's Tenderizer": "https://diablo2.io/uniques/nord-s-tenderizer-t867.html",
  "Nosferatu's Coil": "https://diablo2.io/uniques/nosferatu-s-coil-t868.html",
  "Ondal's Almighty": "https://diablo2.io/sets/ondal-s-almighty-t1085.html",
  "Ondal's Wisdom": "https://diablo2.io/uniques/ondal-s-wisdom-t869.html",
  "Ormus' Robes": "https://diablo2.io/uniques/ormus-robes-t870.html",
  "Orphan's Call": "https://diablo2.io/sets/orphan-s-call-t1133.html",
  "Peasant Crown": "https://diablo2.io/uniques/peasant-crown-t871.html",
  "Pelta Lunata": "https://diablo2.io/uniques/pelta-lunata-t872.html",
  "Pierre Tombale Couant": "https://diablo2.io/uniques/pierre-tombale-couant-t873.html",
  "Plague Bearer": "https://diablo2.io/uniques/plague-bearer-t874.html",
  "Pluckeye": "https://diablo2.io/uniques/pluckeye-t875.html",
  "Pompeii's Wrath": "https://diablo2.io/uniques/pompeii-s-wrath-t876.html",
  "Pus Spitter": "https://diablo2.io/uniques/pus-spitter-t877.html",
  "Que-Hegan's Wisdom": "https://diablo2.io/uniques/que-hegan-s-wisdom-t878.html",
  "Radament's Sphere": "https://diablo2.io/uniques/radament-s-sphere-t879.html",
  "Rainbow Facet: Cold Death": "https://diablo2.io/uniques/rainbow-facet-cold-death-t3169.html",
  "Rainbow Facet: Cold Level-up": "https://diablo2.io/uniques/rainbow-facet-cold-level-up-t3168.html",
  "Rainbow Facet: Fire Death": "https://diablo2.io/uniques/rainbow-facet-fire-death-t3162.html",
  "Rainbow Facet: Fire Level-up": "https://diablo2.io/uniques/rainbow-facet-fire-level-up-t3160.html",
  "Rainbow Facet: Lightning Death": "https://diablo2.io/uniques/rainbow-facet-lightning-death-t3167.html",
  "Rainbow Facet: Lightning Level-up": "https://diablo2.io/uniques/rainbow-facet-lightning-level-up-t3166.html",
  "Rainbow Facet: Poison Death": "https://diablo2.io/uniques/rainbow-facet-poison-death-t3165.html",
  "Rainbow Facet: Poison Level-up": "https://diablo2.io/uniques/rainbow-facet-poison-level-up-t3164.html",
  "Rakescar": "https://diablo2.io/uniques/rakescar-t881.html",
  "Rattlecage": "https://diablo2.io/uniques/rattlecage-t882.html",
  "Raven Claw": "https://diablo2.io/uniques/raven-claw-t883.html",
  "Raven Frost": "https://diablo2.io/uniques/raven-frost-t884.html",
  "Ravenlore": "https://diablo2.io/uniques/ravenlore-t885.html",
  "Razor's Edge": "https://diablo2.io/uniques/razor-s-edge-t886.html",
  "Razorswitch": "https://diablo2.io/uniques/razorswitch-t257.html",
  "Razortail": "https://diablo2.io/uniques/razortail-t887.html",
  "Razortine": "https://diablo2.io/uniques/razortine-t888.html",
  "Ribcracker": "https://diablo2.io/uniques/ribcracker-t889.html",
  "Riphook": "https://diablo2.io/uniques/riphook-t890.html",
  "Ripsaw": "https://diablo2.io/uniques/ripsaw-t891.html",
  "Rite of Passage": "https://diablo2.io/sets/rite-of-passage-t1169.html",
  "Rixot's Keen": "https://diablo2.io/uniques/rixot-s-keen-t892.html",
  "Rockfleece": "https://diablo2.io/uniques/rockfleece-t893.html",
  "Rockstopper": "https://diablo2.io/uniques/rockstopper-t894.html",
  "Rogue's Bow": "https://diablo2.io/uniques/rogue-s-bow-t895.html",
  "Rune Master": "https://diablo2.io/uniques/rune-master-t896.html",
  "Rusthandle": "https://diablo2.io/uniques/rusthandle-t897.html",
  "Sander's Folly": "https://diablo2.io/sets/sander-s-folly-t1138.html",
  "Sander's Paragon": "https://diablo2.io/sets/sander-s-paragon-t1139.html",
  "Sander's Riprap": "https://diablo2.io/sets/sander-s-riprap-t1141.html",
  "Sander's Superstition": "https://diablo2.io/sets/sander-s-superstition-t60.html",
  "Sander's Taboo": "https://diablo2.io/sets/sander-s-taboo-t1140.html",
  "Sandstorm Trek": "https://diablo2.io/uniques/sandstorm-trek-t898.html",
  "Saracen's Chance": "https://diablo2.io/uniques/saracen-s-chance-t899.html",
  "Sazabi's Cobalt Redeemer": "https://diablo2.io/sets/sazabi-s-cobalt-redeemer-t1143.html",
  "Sazabi's Ghost Liberator": "https://diablo2.io/sets/sazabi-s-ghost-liberator-t1144.html",
  "Sazabi's Grand Tribute": "https://diablo2.io/sets/sazabi-s-grand-tribute-t1142.html",
  "Sazabi's Mental Sheath": "https://diablo2.io/sets/sazabi-s-mental-sheath-t1145.html",
  "Schaefer's Hammer": "https://diablo2.io/uniques/schaefer-s-hammer-t900.html",
  "Seraph's Hymn": "https://diablo2.io/uniques/seraph-s-hymn-t41.html",
  "Serpent Lord": "https://diablo2.io/uniques/serpent-lord-t901.html",
  "Shadow Dancer": "https://diablo2.io/uniques/shadow-dancer-t902.html",
  "Shadow Killer": "https://diablo2.io/uniques/shadow-killer-t903.html",
  "Shadowfang": "https://diablo2.io/uniques/shadowfang-t904.html",
  "Shaftstop": "https://diablo2.io/uniques/shaftstop-t905.html",
  "Sigon's Complete Steel": "https://diablo2.io/sets/sigon-s-complete-steel-t1146.html",
  "Sigon's Gage": "https://diablo2.io/sets/sigon-s-gage-t1150.html",
  "Sigon's Guard": "https://diablo2.io/sets/sigon-s-guard-t1149.html",
  "Sigon's Sabot": "https://diablo2.io/sets/sigon-s-sabot-t1151.html",
  "Sigon's Shelter": "https://diablo2.io/sets/sigon-s-shelter-t1147.html",
  "Sigon's Visor": "https://diablo2.io/sets/sigon-s-visor-t1148.html",
  "Sigon's Wrap": "https://diablo2.io/sets/sigon-s-wrap-t1152.html",
  "Silks of the Victor": "https://diablo2.io/uniques/silks-of-the-victor-t2.html",
  "Silkweave": "https://diablo2.io/uniques/silkweave-t906.html",
  "Skewer of Krintiz": "https://diablo2.io/uniques/skewer-of-krintiz-t907.html",
  "Skin of the Flayed One": "https://diablo2.io/uniques/skin-of-the-flayed-one-t908.html",
  "Skin of the Vipermagi": "https://diablo2.io/uniques/skin-of-the-vipermagi-t909.html",
  "Skull Collector": "https://diablo2.io/uniques/skull-collector-t910.html",
  "Skull Splitter": "https://diablo2.io/uniques/skull-splitter-t911.html",
  "Skullder's Ire": "https://diablo2.io/uniques/skullder-s-ire-t912.html",
  "Skystrike": "https://diablo2.io/uniques/skystrike-t913.html",
  "Snakecord": "https://diablo2.io/uniques/snakecord-t914.html",
  "Snowclash": "https://diablo2.io/uniques/snowclash-t915.html",
  "Soul Drainer": "https://diablo2.io/uniques/soul-drainer-t916.html",
  "Soul Harvest": "https://diablo2.io/uniques/soul-harvest-t36.html",
  "Soulfeast Tine": "https://diablo2.io/uniques/soulfeast-tine-t917.html",
  "Soulflay": "https://diablo2.io/uniques/soulflay-t918.html",
  "Sparking Mail": "https://diablo2.io/uniques/sparking-mail-t919.html",
  "Spectral Shard": "https://diablo2.io/uniques/spectral-shard-t920.html",
  "Spellsteel": "https://diablo2.io/uniques/spellsteel-t921.html",
  "Spike Thorn": "https://diablo2.io/uniques/spike-thorn-t922.html",
  "Spineripper": "https://diablo2.io/uniques/spineripper-t923.html",
  "Spire of Honor": "https://diablo2.io/uniques/spire-of-honor-t924.html",
  "Spire of Lazarus": "https://diablo2.io/uniques/spire-of-lazarus-t925.html",
  "Spirit Forge": "https://diablo2.io/uniques/spirit-forge-t926.html",
  "Spirit Keeper": "https://diablo2.io/uniques/spirit-keeper-t927.html",
  "Spirit Ward": "https://diablo2.io/uniques/spirit-ward-t928.html",
  "Stealskull": "https://diablo2.io/uniques/stealskull-t929.html",
  "Steel Carapace": "https://diablo2.io/uniques/steel-carapace-t930.html",
  "Steel Pillar": "https://diablo2.io/uniques/steel-pillar-t931.html",
  "Steel Shade": "https://diablo2.io/uniques/steel-shade-t932.html",
  "Steelclash": "https://diablo2.io/uniques/steelclash-t933.html",
  "Steeldriver": "https://diablo2.io/uniques/steeldriver-t934.html",
  "Steelgoad": "https://diablo2.io/uniques/steelgoad-t935.html",
  "Steelrend": "https://diablo2.io/uniques/steelrend-t936.html",
  "Stone Crusher": "https://diablo2.io/uniques/stone-crusher-t937.html",
  "The Stone of Jordan": "https://diablo2.io/uniques/stone-of-jordan-t938.html",
  "Stoneraven": "https://diablo2.io/uniques/stoneraven-t939.html",
  "Stormchaser": "https://diablo2.io/uniques/stormchaser-t940.html",
  "Stormeye": "https://diablo2.io/uniques/stormeye-t941.html",
  "Stormguild": "https://diablo2.io/uniques/stormguild-t942.html",
  "Stormlash": "https://diablo2.io/uniques/stormlash-t943.html",
  "Stormrider": "https://diablo2.io/uniques/stormrider-t944.html",
  "Stormshield": "https://diablo2.io/uniques/stormshield-t945.html",
  "Stormspike": "https://diablo2.io/uniques/stormspike-t946.html",
  "Stormspire": "https://diablo2.io/uniques/stormspire-t947.html",
  "Stormstrike": "https://diablo2.io/uniques/stormstrike-t948.html",
  "Stoutnail": "https://diablo2.io/uniques/stoutnail-t949.html",
  "String of Ears": "https://diablo2.io/uniques/string-of-ears-t950.html",
  "Suicide Branch": "https://diablo2.io/uniques/suicide-branch-t951.html",
  "Sureshrill Frost": "https://diablo2.io/uniques/sureshrill-frost-t952.html",
  "Swordback Hold": "https://diablo2.io/uniques/swordback-hold-t953.html",
  "Swordguard": "https://diablo2.io/uniques/swordguard-t954.html",
  "Taebaek's Glory": "https://diablo2.io/sets/taebaek-s-glory-t1084.html",
  "Tal Rasha's Adjudication": "https://diablo2.io/sets/tal-rasha-s-adjudication-t1154.html",
  "Tal Rasha's Fine Spun Cloth": "https://diablo2.io/sets/tal-rasha-s-fine-spun-cloth-t1158.html",
  "Tal Rasha's Guardianship": "https://diablo2.io/sets/tal-rasha-s-guardianship-t1156.html",
  "Tal Rasha's Horadric Crest": "https://diablo2.io/sets/tal-rasha-s-horadric-crest-t1157.html",
  "Tal Rasha's Lidless Eye": "https://diablo2.io/sets/tal-rasha-s-lidless-eye-t1155.html",
  "Tal Rasha's Wrappings": "https://diablo2.io/sets/tal-rasha-s-wrappings-t1153.html",
  "Tancred's Battlegear": "https://diablo2.io/sets/tancred-s-battlegear-t1159.html",
  "Tancred's Crowbill": "https://diablo2.io/sets/tancred-s-crowbill-t1164.html",
  "Tancred's Hobnails": "https://diablo2.io/sets/tancred-s-hobnails-t1162.html",
  "Tancred's Skull": "https://diablo2.io/sets/tancred-s-skull-t1160.html",
  "Tancred's Spine": "https://diablo2.io/sets/tancred-s-spine-t1163.html",
  "Tancred's Weird": "https://diablo2.io/sets/tancred-s-weird-t1161.html",
  "Tarnhelm": "https://diablo2.io/uniques/tarnhelm-t955.html",
  "Tearhaunch": "https://diablo2.io/uniques/tearhaunch-t956.html",
  "Telling of Beads": "https://diablo2.io/sets/telling-of-beads-t1170.html",
  "Templar's Might": "https://diablo2.io/uniques/templar-s-might-t957.html",
  "The Atlantean": "https://diablo2.io/uniques/the-atlantean-t958.html",
  "The Battlebranch": "https://diablo2.io/uniques/the-battlebranch-t959.html",
  "The Cat's Eye": "https://diablo2.io/uniques/the-cat-s-eye-t960.html",
  "The Centurion": "https://diablo2.io/uniques/the-centurion-t961.html",
  "The Chieftain": "https://diablo2.io/uniques/the-chieftain-t962.html",
  "The Cranium Basher": "https://diablo2.io/uniques/the-cranium-basher-t963.html",
  "The Diggler": "https://diablo2.io/uniques/the-diggler-t964.html",
  "The Disciple": "https://diablo2.io/sets/the-disciple-t1165.html",
  "The Dragon Chang": "https://diablo2.io/uniques/the-dragon-chang-t965.html",
  "The Eye of Etlich": "https://diablo2.io/uniques/the-eye-of-etlich-t966.html",
  "The Face of Horror": "https://diablo2.io/uniques/the-face-of-horror-t967.html",
  "The Fetid Sprinkler": "https://diablo2.io/uniques/the-fetid-sprinkler-t968.html",
  "The Gavel of Pain": "https://diablo2.io/uniques/the-gavel-of-pain-t969.html",
  "The General's Tan Do Li Ga": "https://diablo2.io/uniques/the-general-s-tan-do-li-ga-t970.html",
  "The Gladiator's Bane": "https://diablo2.io/uniques/the-gladiator-s-bane-t971.html",
  "The Gnasher": "https://diablo2.io/uniques/the-gnasher-t972.html",
  "The Grandfather": "https://diablo2.io/uniques/the-grandfather-t973.html",
  "The Grim Reaper": "https://diablo2.io/uniques/the-grim-reaper-t974.html",
  "The Hand of Broc": "https://diablo2.io/uniques/the-hand-of-broc-t975.html",
  "The Impaler": "https://diablo2.io/uniques/the-impaler-t976.html",
  "The Iron Jang Bong": "https://diablo2.io/uniques/the-iron-jang-bong-t977.html",
  "The Jade Tan Do": "https://diablo2.io/uniques/the-jade-tan-do-t978.html",
  "The Mahim-Oak Curio": "https://diablo2.io/uniques/the-mahim-oak-curio-t979.html",
  "The Meat Scraper": "https://diablo2.io/uniques/the-meat-scraper-t980.html",
  "The Minotaur": "https://diablo2.io/uniques/the-minotaur-t981.html",
  "The Oculus": "https://diablo2.io/uniques/the-oculus-t982.html",
  "The Patriarch": "https://diablo2.io/uniques/the-patriarch-t983.html",
  "The Reaper's Toll": "https://diablo2.io/uniques/the-reaper-s-toll-t984.html",
  "The Redeemer": "https://diablo2.io/uniques/the-redeemer-t985.html",
  "The Rising Sun": "https://diablo2.io/uniques/the-rising-sun-t986.html",
  "The Salamander": "https://diablo2.io/uniques/the-salamander-t987.html",
  "The Scalper": "https://diablo2.io/uniques/the-scalper-t988.html",
  "The Spirit Shroud": "https://diablo2.io/uniques/the-spirit-shroud-t989.html",
  "The Tannr Gorerod": "https://diablo2.io/uniques/the-tannr-gorerod-t990.html",
  "The Vile Husk": "https://diablo2.io/uniques/the-vile-husk-t991.html",
  "The Ward": "https://diablo2.io/uniques/the-ward-t992.html",
  "Thundergod's Vigor": "https://diablo2.io/uniques/thundergod-s-vigor-t38.html",
  "Thunderstroke": "https://diablo2.io/uniques/thunderstroke-t993.html",
  "Tiamat's Rebuke": "https://diablo2.io/uniques/tiamat-s-rebuke-t994.html",
  "Titan's Revenge": "https://diablo2.io/uniques/titan-s-revenge-t995.html",
  "Todesfaelle Flamme": "https://diablo2.io/uniques/todesfaelle-flamme-t996.html",
  "Tomb Reaver": "https://diablo2.io/uniques/tomb-reaver-t997.html",
  "Toothrow": "https://diablo2.io/uniques/toothrow-t998.html",
  "Torch of Iro": "https://diablo2.io/uniques/torch-of-iro-t999.html",
  "Trang-Oul's Avatar": "https://diablo2.io/sets/trang-oul-s-avatar-t1171.html",
  "Trang-Oul's Claws": "https://diablo2.io/sets/trang-oul-s-claws-t1175.html",
  "Trang-Oul's Girth": "https://diablo2.io/sets/trang-oul-s-girth-t1174.html",
  "Trang-Oul's Guise": "https://diablo2.io/sets/trang-oul-s-guise-t1172.html",
  "Trang-Oul's Scales": "https://diablo2.io/sets/trang-oul-s-scales-t1173.html",
  "Trang-Oul's Wing": "https://diablo2.io/sets/trang-oul-s-wing-t1176.html",
  "Treads of Cthon": "https://diablo2.io/uniques/treads-of-cthon-t1000.html",
  "Twitchthroe": "https://diablo2.io/uniques/twitchthroe-t1001.html",
  "Tyrael's Might": "https://diablo2.io/uniques/tyrael-s-might-t1002.html",
  "Umbral Disk": "https://diablo2.io/uniques/umbral-disk-t1003.html",
  "Ume's Lament": "https://diablo2.io/uniques/ume-s-lament-t1004.html",
  "Undead Crown": "https://diablo2.io/uniques/undead-crown-t1005.html",
  "Valkyrie Wing": "https://diablo2.io/uniques/valkyrie-wing-t1006.html",
  "Vampire Gaze": "https://diablo2.io/uniques/vampire-gaze-t1007.html",
  "Veil of Steel": "https://diablo2.io/uniques/veil-of-steel-t1008.html",
  "Venom Grip": "https://diablo2.io/uniques/venom-grip-t1009.html",
  "Venom Ward": "https://diablo2.io/uniques/venom-ward-t1010.html",
  "Verdungo's Hearty Cord": "https://diablo2.io/uniques/verdungo-s-hearty-cord-t1011.html",
  "Vidala's Ambush": "https://diablo2.io/sets/vidala-s-ambush-t1179.html",
  "Vidala's Barb": "https://diablo2.io/sets/vidala-s-barb-t1181.html",
  "Vidala's Fetlock": "https://diablo2.io/sets/vidala-s-fetlock-t1180.html",
  "Vidala's Rig": "https://diablo2.io/sets/vidala-s-rig-t1177.html",
  "Vidala's Snare": "https://diablo2.io/sets/vidala-s-snare-t1178.html",
  "Viperfork": "https://diablo2.io/uniques/viperfork-t1012.html",
  "Visceratuant": "https://diablo2.io/uniques/visceratuant-t1013.html",
  "Wall of the Eyeless": "https://diablo2.io/uniques/wall-of-the-eyeless-t1014.html",
  "War Traveler": "https://diablo2.io/uniques/war-traveler-t1015.html",
  "Warlord's Trust": "https://diablo2.io/uniques/warlord-s-trust-t1016.html",
  "Warpspear": "https://diablo2.io/uniques/warpspear-t1017.html",
  "Warshrike": "https://diablo2.io/uniques/warshrike-t1018.html",
  "Waterwalk": "https://diablo2.io/uniques/waterwalk-t1019.html",
  "Whitstan's Guard": "https://diablo2.io/sets/whitstan-s-guard-t1134.html",
  "Widowmaker": "https://diablo2.io/uniques/widowmaker-t1020.html",
  "Wilhelm's Pride": "https://diablo2.io/sets/wilhelm-s-pride-t1136.html",
  "Windforce": "https://diablo2.io/uniques/windforce-t1021.html",
  "Windhammer": "https://diablo2.io/uniques/windhammer-t1022.html",
  "Wisp Projector": "https://diablo2.io/uniques/wisp-projector-t1023.html",
  "Witchwild String": "https://diablo2.io/uniques/witchwild-string-t1024.html",
  "Witherstring": "https://diablo2.io/uniques/witherstring-t1025.html",
  "Wizardspike": "https://diablo2.io/uniques/wizardspike-t1026.html",
  "Wizendraw": "https://diablo2.io/uniques/wizendraw-t1027.html",
  "Woestave": "https://diablo2.io/uniques/woestave-t1028.html",
  "Wolfhowl": "https://diablo2.io/uniques/wolfhowl-t1029.html",
  "Wormskull": "https://diablo2.io/uniques/wormskull-t1030.html",
  "Wraith Flight": "https://diablo2.io/uniques/wraith-flight-t1031.html",
  "Zakarum's Hand": "https://diablo2.io/uniques/zakarum-s-hand-t1032.html"
}