export const silospenMapping: {[itemName: string]: string} = {
  'Alma Negra': 'Alma Negra',
  "Andariel's Visage": "Andariel's Visage",
  Annihilus: 'Annihilus',
  'Arachnid Mesh': 'Arachnid Mesh',
  "Arioc's Needle": "Arioc's Needle",
  "Arkaine's Valor": "Arkaine's Valor",
  'Arm of King Leoric': 'Arm of King Leoric',
  "Arreat's Face": "Arreat's Face",
  "Astreon's Iron Ward": 'Ironward',
  "Athena's Wrath": "Athena's Wrath",
  "Atma's Scarab": "Atma's Scarab",
  "Atma's Wail": "Atma's Wail",
  'Axe of Fechmar': 'Fechmars Axe',
  Azurewrath: 'Azurewrath',
  "Baezil's Vortex": "Baezil's Vortex",
  'Bane Ash': 'Bane Ash',
  "Baranar's Star": "Baranar's Star",
  "Bartuc's Cut-Throat": 'Cutthroat1',
  "Biggin's Bonnet": 'War Bonnet',
  'Bing Sz Wang': 'Bing Sz Wang',
  'Black Hades': 'Black Hades',
  "Blackbog's Sharp": "Blackbog's Sharp",
  'Blackhand Key': 'Blackhand Key',
  "Blackhorn's Face": "Blackhorn's Face",
  'Blackleach Blade': 'Blackleach Blade',
  'Blackoak Shield': 'Blackoak Shield',
  Blacktongue: 'Blacktongue',
  'Blade of Ali Baba': 'Blade of Ali Baba',
  Bladebone: 'Bladebone',
  Bladebuckle: 'Bladebuckle',
  Blastbark: 'Blastbark',
  "Blinkbat's Form": 'Blinkbats Form',
  'Blood Crescent': 'Blood Crescent',
  "Blood Raven's Charge": "Bloodraven's Charge",
  Bloodfist: 'Bloodfist',
  Bloodletter: 'Bloodletter',
  Bloodmoon: 'Bloodmoon',
  Bloodrise: 'Bloodrise',
  Bloodthief: 'Bloodthief',
  'Bloodtree Stump': 'Bloodtree Stump',
  Boneflame: 'Boneflame',
  Boneflesh: 'Boneflesh',
  Bonehew: 'Bonehew',
  Boneshade: 'Boneshade',
  'Boneslayer Blade': 'Boneslayer Blade',
  Bonesnap: 'Bonesob',
  Brainhew: 'Brainhew',
  "Bul-Kathos' Wedding Band": "Bul Katho's Wedding Band",
  'Buriza-Do Kyanon': 'Buriza-Do Kyanon',
  "Butcher's Pupil": "Butcher's Pupil",
  'Bverrit Keep': 'Bverrit Keep',
  'Carin Shard': 'Carin Shard',
  'Carrion Wind': 'Carrion Wind',
  "Cerebus' Bite": 'Cerebus',
  'Chance Guards': 'Chance Guards',
  'Chromatic Ire': 'Chromatic Ire',
  Cliffkiller: 'Cliffkiller',
  Cloudcrack: 'Cloudcrack',
  'Coif of Glory': 'Coif of Glory',
  Coldkill: 'Coldkill',
  'Coldsteel Eye': 'Coldsteel Eye',
  Corpsemourn: 'Corpsemourn',
  'Crainte Vomir': 'Crainte Vomir',
  Cranebeak: 'Cranebeak',
  'Crescent Moon': 'Crescent Moon',
  'Crow Caw': 'Crow Caw',
  'Crown of Ages': 'Crown of Ages',
  'Crown of Thieves': 'Crown of Thieves',
  Crushflange: 'Crushflange',
  "Culwen's Point": 'Culwens Point',
  'Dark Clan Crusher': 'Dark Clan Crusher',
  'Darkforce Spawn': 'Darkforge Spawn',
  Darkglow: 'Darkglow',
  'Darksight Helm': 'Darksight Helm',
  'Death Cleaver': 'Deathcleaver',
  "Death's Fathom": 'Fathom',
  "Death's Web": "Deaths's Web",
  Deathbit: 'Deathbit',
  Deathspade: 'Deathspade',
  'Demon Limb': 'Demonlimb',
  'Demon Machine': 'Demon Machine',
  "Demon's Arch": "Demon's Arch",
  "Demonhorn's Edge": "Demonhorn's Edge",
  "Dimoak's Hew": 'Dimoaks Hew',
  'Djinn Slayer': 'Djinnslayer',
  Doombringer: 'Doombringer',
  Doomslinger: 'Doomspittle',
  "Dracul's Grasp": "Dracul's Grasp",
  Dragonscale: 'Dragonscale',
  "Duriel's Shell": "Duriel's Shell",
  Duskdeep: 'Duskdeep',
  'Dwarf Star': 'Dwarf Star',
  Eaglehorn: 'Eaglehorn',
  'Earth Shifter': 'Earthshifter',
  Earthshaker: 'Earthshaker',
  Endlesshail: 'Endlesshail',
  "Eschuta's Temper": "Eschuta's temper",
  'Ethereal Edge': 'Ethereal Edge',
  "Executioner's Justice": "Executioner's Justice",
  Felloak: 'Felloak',
  "Firelizard's Talons": "Firelizard's Talons",
  Flamebellow: 'Flamebellow',
  Fleshrender: 'Fleshrender',
  Fleshripper: 'Fleshripper',
  Frostburn: 'Frostburn',
  Frostwind: 'Frostwind',
  "Gargoyle's Bite": "Gargoyle's Bite",
  "Gerke's Sanctuary": "Kerke's Sanctuary",
  "Gheed's Fortune": "Gheed's Fortune",
  Ghostflame: 'Ghostflame',
  Ghoulhide: 'Ghoulhide',
  'Giant Skull': 'Giantskull',
  Gimmershred: 'Gimmershred',
  "Ginther's Rift": "Ginther's Rift",
  Gleamscythe: 'Gleamscythe',
  "Gloom's Trap": 'Gloomstrap',
  'Goblin Toe': 'Goblin Toe',
  Goldskin: 'Goldskin',
  'Goldstrike Arch': 'Godstrike Arch',
  Goldwrap: 'Goldwrap',
  'Gore Rider': 'Gorerider',
  Gorefoot: 'Gorefoot',
  Goreshovel: 'Goreshovel',
  Gravenspine: 'Gravenspine',
  Gravepalm: 'Gravepalm',
  Greyform: 'Greyform',
  "Griffon's Eye": "Griffon's Eye",
  "Grim's Burning Dead": "Grim's Burning Dead",
  "Griswold's Edge": 'Griswolds Edge',
  'Guardian Angel': 'Guardian Angel',
  'Guardian Naga': 'Guardian Naga',
  Gull: 'Gull',
  'Gut Siphon': 'Gutsiphon',
  "Halaberd's Reign": "Halaberd's Reign",
  'Hand of Blessed Light': 'Hand of Blessed Light',
  'Harlequin Crest': 'Harlequin Crest',
  Hawkmail: 'Hawkmail',
  "Head Hunter's Glory": "Headhunter's Glory",
  Headstriker: 'Headstriker',
  'Heart Carver': 'Heart Carver',
  "Heaven's Light": "Heaven's Light",
  'Heavenly Garb': 'Heavenly Garb',
  Hellcast: 'Hellcast',
  Hellclap: 'Hellclap',
  'Hellfire Torch': 'Hellfire Torch',
  Hellmouth: 'Hellmouth',
  Hellplague: 'Hellplague',
  Hellrack: 'Hellrack',
  Hellslayer: 'Hellslayer',
  'Herald of Zakarum': 'Herald of Zakarum',
  Hexfire: 'Hexfire',
  "Highlord's Wrath": "Highlord's Wrath",
  Homunculus: 'Homunculus',
  'Hone Sundan': 'Hone Sundan',
  "Horizon's Tornado": "Horizon's Tornado",
  Hotspur: 'Hotspur',
  Howltusk: 'Howltusk',
  Humongous: 'The Humongous',
  'Husoldal Evo': 'Husoldal Evo',
  Iceblink: 'Iceblink',
  Ichorsting: 'Ichorsting',
  Infernostride: 'Infernostride',
  'Iron Pelt': 'Ironpelt',
  Ironstone: 'Ironstone',
  Islestrike: 'Islestrike',
  'Jade Talon': 'Jadetalon',
  "Jalal's Mane": "Jalal's Mane",
  'Kelpie Snare': 'Kelpie Snare',
  "Kinemil's Awl": 'Kinemils Awl',
  "Kira's Guardian": "Kira's Guardian",
  'Knell Striker': 'Knell Striker',
  'Kuko Shakaku': 'Kuko Shakaku',
  Lacerator: 'Lacerator',
  'Lance Guard': 'Lance Guard',
  'Lance of Yaggai': 'Lance of Yaggai',
  'Langer Briser': 'Langer Briser',
  'Lava Gout': 'Lavagout',
  Leadcrow: 'Leadcrow',
  Lenymo: 'Lenyms Cord',
  Leviathan: 'Leviathan',
  'Lidless Wall': 'Lidless Wall',
  Lightsabre: 'Lightsabre',
  "Lycander's Aim": "Lycander's Aim",
  "Lycander's Flank": "Lycander's Flank",
  Maelstrom: 'Maelstromwrath',
  Magefist: 'Magefist',
  Magewrath: 'Magewrath',
  'Manald Heal': 'Manald Heal',
  "Mang Song's Lesson": "Mang Song's Lesson",
  "Mara's Kaleidoscope": "Mara's Kaleidoscope",
  Marrowwalk: 'Marrowwalk',
  "Medusa's Gaze": "Medusa's Gaze",
  "Messerschmidt's Reaver": "Messerschmidt's Reaver",
  Metalgrid: 'Metalgrid',
  Moonfall: 'Moonfall',
  "Moser's Blessed Circle": 'Mosers Blessed Circle',
  Nagelring: 'Nagelring',
  "Nature's Peace": "Nature's Peace",
  Nightsmoke: 'Nightsmoke',
  "Nightwing's Veil": "Nightwing's Veil",
  'Nokozan Relic': 'Nokozan Relic',
  "Nord's Tenderizer": "Nord's Tenderizer",
  "Nosferatu's Coil": "Nosferatu's Coil",
  "Ondal's Wisdom": "Ondal's Wisdom",
  "Ormus' Robes": "Ormus' Robes",
  'Peasant Crown': 'Peasent Crown',
  'Pelta Lunata': 'Pelta Lunata',
  'Pierre Tombale Couant': 'Pierre Tombale Couant',
  'Plague Bearer': 'Plague Bearer',
  Pluckeye: 'Pluckeye',
  "Pompeii's Wrath": "Pompe's Wrath",
  'Pus Spitter': 'Pus Spiter',
  "Que-Hegan's Wisdom": "Que-Hegan's Wisdon",
  "Radament's Sphere": "Radimant's Sphere",
  "Rainbow Facet: Cold Death": "Rainbow Facet",
  "Rainbow Facet: Cold Level-up": "Rainbow Facet",
  "Rainbow Facet: Fire Death": "Rainbow Facet",
  "Rainbow Facet: Fire Level-up": "Rainbow Facet",
  "Rainbow Facet: Lightning Death": "Rainbow Facet",
  "Rainbow Facet: Lightning Level-up": "Rainbow Facet",
  "Rainbow Facet: Poison Death": "Rainbow Facet",
  "Rainbow Facet: Poison Level-up": "Rainbow Facet",
  Rakescar: 'Rakescar',
  Rattlecage: 'Rattlecage',
  'Raven Claw': 'Rimeraven',
  'Raven Frost': 'Raven Frost',
  Ravenlore: 'Ravenlore',
  "Razor's Edge": 'Razoredge',
  Razorswitch: 'Razorswitch',
  Razortail: 'Razortail',
  Razortine: 'Razortine',
  Ribcracker: 'Ribcracker',
  Riphook: 'Riphook',
  Ripsaw: 'Ripsaw',
  "Rixot's Keen": 'Rixots Keen',
  Rockfleece: 'Rockfleece',
  Rockstopper: 'Rockstopper',
  "Rogue's Bow": 'Piercerib',
  'Rune Master': 'Runemaster',
  Rusthandle: 'Rusthandle',
  'Sandstorm Trek': 'Sandstorm Trek',
  "Saracen's Chance": "Saracen's Chance",
  "Schaefer's Hammer": "Schaefer's Hammer",
  "Seraph's Hymn": "Seraph's Hymn",
  'Serpent Lord': 'Serpent Lord',
  'Shadow Dancer': 'Shadowdancer',
  'Shadow Killer': 'Shadowkiller',
  Shadowfang: 'Shadowfang',
  Shaftstop: 'Shaftstop',
  'Silks of the Victor': 'Victors Silk',
  Silkweave: 'Silkweave',
  'Skewer of Krintiz': 'Krintizs Skewer',
  'Skin of the Flayed One': 'Skin of the Flayerd One',
  'Skin of the Vipermagi': 'Skin of the Vipermagi',
  'Skull Collector': 'Skullcollector',
  'Skull Splitter': 'Mindrend',
  "Skullder's Ire": "Skullder's Ire",
  Skystrike: 'Skystrike',
  Snakecord: 'Snakecord',
  Snowclash: 'Snowclash',
  'Soul Drainer': 'Souldrain',
  'Soul Harvest': 'Soul Harvest',
  'Soulfeast Tine': 'Soulfeast Tine',
  Soulflay: 'Soulflay',
  'Sparking Mail': 'Sparking Mail',
  'Spectral Shard': 'Irices Shard',
  Spellsteel: 'Spellsteel',
  'Spike Thorn': 'Spike Thorn',
  Spineripper: 'Spineripper',
  'Spire of Honor': 'Spire of Honor',
  'Spire of Lazarus': 'Lazarus Spire',
  'Spirit Forge': 'Spiritforge',
  'Spirit Keeper': 'Spiritkeeper',
  'Spirit Ward': 'Spirit Ward',
  Stealskull: 'Stealskull',
  'Steel Carapace': 'Steel Carapice',
  'Steel Pillar': 'Steelpillar',
  'Steel Shade': 'Steelshade',
  Steelclash: 'Steelclash',
  Steeldriver: 'Steeldriver',
  Steelgoad: 'Steelgoad',
  Steelrend: 'Steelrend',
  'Stone Crusher': 'Stone Crusher',
  Stoneraven: 'Stoneraven',
  Stormchaser: 'Stormchaser',
  Stormeye: 'Stormeye',
  Stormguild: 'Stormguild',
  Stormlash: 'Stormlash',
  Stormrider: 'Stormrider',
  Stormshield: 'Stormshield',
  Stormspike: 'Stormspike',
  Stormspire: 'Stormspire',
  Stormstrike: 'Pullspite',
  Stoutnail: 'Stoutnail',
  'String of Ears': 'String of Ears',
  'Suicide Branch': 'Suicide Branch',
  'Sureshrill Frost': 'Sureshrill Frost',
  'Swordback Hold': 'Swordback Hold',
  Swordguard: 'Swordguard',
  Tarnhelm: 'Tarnhelm',
  Tearhaunch: 'Tearhaunch',
  "Templar's Might": "Templar's Might",
  'The Atlantean': 'The Atlantian',
  'The Battlebranch': 'The Battlebranch',
  "The Cat's Eye": "The Cat's Eye",
  'The Centurion': 'The Centurion',
  'The Chieftain': 'The Chieftan',
  'The Cranium Basher': 'The Cranium Basher',
  'The Diggler': 'The Diggler',
  'The Dragon Chang': 'The Dragon Chang',
  'The Eye of Etlich': 'The Eye of Etlich',
  'The Face of Horror': 'The Face of Horror',
  'The Fetid Sprinkler': 'The Fetid Sprinkler',
  'The Gavel of Pain': 'The Gavel of Pain',
  "The General's Tan Do Li Ga": 'The Generals Tan Do Li Ga',
  "The Gladiator's Bane": "The Gladiator's Bane",
  'The Gnasher': 'The Gnasher',
  'The Grandfather': 'The Grandfather',
  'The Grim Reaper': 'The Grim Reaper',
  'The Hand of Broc': 'The Hand of Broc',
  'The Impaler': 'The Impaler',
  'The Iron Jang Bong': 'The Iron Jang Bong',
  'The Jade Tan Do': 'The Jade Tan Do',
  'The Mahim-Oak Curio': 'The Mahim-Oak Curio',
  'The Meat Scraper': 'The Meat Scraper',
  'The Minotaur': 'The Minataur',
  'The Oculus': 'The Oculus',
  'The Patriarch': 'The Patriarch',
  "The Reaper's Toll": "The Reaper's Toll",
  'The Redeemer': 'The Reedeemer',
  'The Rising Sun': 'The Rising Sun',
  'The Salamander': 'The Salamander',
  'The Scalper': 'The Scalper',
  'The Spirit Shroud': 'The Spirit Shroud',
  'The Stone of Jordan': 'The Stone of Jordan',
  'The Tannr Gorerod': 'The Tannr Gorerod',
  'The Vile Husk': 'The Vile Husk',
  'The Ward': 'The Ward',
  "Thundergod's Vigor": "Thudergod's Vigor",
  Thunderstroke: 'Thunderstroke',
  "Tiamat's Rebuke": "Tiamat's Rebuke",
  "Titan's Revenge": "Titan's Revenge",
  'Todesfaelle Flamme': 'Todesfaelle Flamme',
  'Tomb Reaver': 'Tomb Reaver',
  Toothrow: 'Toothrow',
  'Torch of Iro': 'Iros Torch',
  'Treads of Cthon': 'Treads of Cthon',
  Twitchthroe: 'Twitchthroe',
  "Tyrael's Might": "Tyrael's Might",
  'Umbral Disk': 'Umbral Disk',
  "Ume's Lament": 'Umes Lament',
  'Undead Crown': 'Undead Crown',
  'Valkyrie Wing': 'Valkiry Wing',
  'Vampire Gaze': 'Vampiregaze',
  'Veil of Steel': 'Veil of Steel',
  'Venom Grip': 'Venom Grip',
  'Venom Ward': 'Venomsward',
  "Verdungo's Hearty Cord": "Verdugo's Hearty Cord",
  Viperfork: 'Viperfork',
  Visceratuant: 'Visceratuant',
  'Wall of the Eyeless': 'Wall of the Eyeless',
  'War Traveler': 'Wartraveler',
  "Warlord's Trust": "Warlord's Trust",
  Warpspear: 'Warpspear',
  Warshrike: 'Warshrike',
  Waterwalk: 'Waterwalk',
  Widowmaker: 'Widowmaker',
  Windforce: 'Windforce',
  Windhammer: 'Windhammer',
  'Wisp Projector': 'Wisp',
  'Witchwild String': 'Whichwild String',
  Witherstring: 'Witherstring',
  Wizardspike: 'Wizardspike',
  Wizendraw: 'Wizendraw',
  Woestave: 'Woestave',
  Wolfhowl: 'Wolfhowl',
  Wormskull: 'Wormskull',
  'Wraith Flight': 'Wraithflight',
  "Zakarum's Hand": "Zakarum's Hand",
  "Aldur's Advance": "Aldur's Advance",
  "Aldur's Deception": "Aldur's Deception",
  "Aldur's Rhythm": "Aldur's Gauntlet",
  "Aldur's Stony Gaze": "Aldur's Stony Gaze",
  'Angelic Halo': 'Angelic Halo',
  'Angelic Mantle': 'Angelic Mantle',
  'Angelic Sickle': 'Angelic Sickle',
  'Angelic Wings': 'Angelic Wings',
  "Arcanna's Deathwand": "Arcanna's Deathwand",
  "Arcanna's Flesh": "Arcanna's Flesh",
  "Arcanna's Head": "Arcanna's Head",
  "Arcanna's Sign": "Arcanna's Sign",
  'Arctic Binding': 'Arctic Binding',
  'Arctic Furs': 'Arctic Furs',
  'Arctic Horn': 'Arctic Horn',
  'Arctic Mitts': 'Arctic Mitts',
  "Berserker's Hatchet": "Berserker's Hatchet",
  "Berserker's Hauberk": "Berserker's Hauberk",
  "Berserker's Headgear": "Berserker's Headgear",
  "Bul-Kathos' Sacred Charge": "Bul-Kathos' Sacred Charge",
  "Bul-Kathos' Tribal Guardian": "Bul-Kathos' Tribal Guardian",
  "Cathan's Mesh": "Cathan's Mesh",
  "Cathan's Rule": "Cathan's Rule",
  "Cathan's Seal": "Cathan's Seal",
  "Cathan's Sigil": "Cathan's Sigil",
  "Cathan's Visage": "Cathan's Visage",
  "Civerb's Cudgel": "Civerb's Cudgel",
  "Civerb's Icon": "Civerb's Icon",
  "Civerb's Ward": "Civerb's Ward",
  "Cleglaw's Claw": "Cleglaw's Claw",
  "Cleglaw's Pincers": "Cleglaw's Pincers",
  "Cleglaw's Tooth": "Cleglaw's Tooth",
  "Cow King's Hide": "Cow King's Hide",
  "Cow King's Hooves": "Cow King's Hoofs",
  "Cow King's Horns": "Cow King's Horns",
  Credendum: 'Credendum',
  "Dangoon's Teaching": "Dangoon's Teaching",
  'Dark Adherent': 'Spiritual Custodian',
  "Death's Guard": "Death's Guard",
  "Death's Hand": "Death's Hand",
  "Death's Touch": "Death's Touch",
  "Griswold's Heart": "Griswold's Heart",
  "Griswold's Honor": "Griswold's Honor",
  "Griswold's Redemption": "Griswolds's Redemption",
  "Griswold's Valor": "Griswold's Valor",
  "Guillaume's Face": "Guillaume's Face",
  "Haemosu's Adamant": "Haemosu's Adament",
  "Hsarus' Iron Fist": "Hsarus' Iron Fist",
  "Hsarus' Iron Heel": "Hsarus' Iron Heel",
  "Hsarus' Iron Stay": "Hsarus' Iron Stay",
  "Hwanin's Blessing": "Hwanin's Seal",
  "Hwanin's Justice": "Hwanin's Justice",
  "Hwanin's Refuge": "Hwanin's Refuge",
  "Hwanin's Splendor": "Hwanin's Splendor",
  "Immortal King's Detail": "Immortal King's Detail",
  "Immortal King's Forge": "Immortal King's Forge",
  "Immortal King's Pillar": "Immortal King's Pillar",
  "Immortal King's Soul Cage": "Immortal King's Soul Cage",
  "Immortal King's Stone Crusher": "Immortal King's Stone Crusher",
  "Immortal King's Will": "Immortal King's Will",
  'Infernal Cranium': 'Infernal Cranium',
  'Infernal Sign': 'Infernal Sign',
  'Infernal Torch': 'Infernal Torch',
  "Iratha's Coil": "Iratha's Coil",
  "Iratha's Collar": "Iratha's Collar",
  "Iratha's Cord": "Iratha's Cord",
  "Iratha's Cuff": "Iratha's Cuff",
  "Isenhart's Case": "Isenhart's Case",
  "Isenhart's Horns": "Isenhart's Horns",
  "Isenhart's Lightbrand": "Isenhart's Lightbrand",
  "Isenhart's Parry": "Isenhart's Parry",
  'Laying of Hands': 'Laying of Hands',
  "M'avina's Caster": "M'avina's Caster",
  "M'avina's Embrace": "M'avina's Embrace",
  "M'avina's Icy Clutch": "M'avina's Icy Clutch",
  "M'avina's Tenet": "M'avina's Tenet",
  "M'avina's True Sight": "M'avina's True Sight",
  "Magnus' Skin": "Magnus' Skin",
  "Milabrega's Diadem": "Milabrega's Diadem",
  "Milabrega's Orb": "Milabrega's Orb",
  "Milabrega's Robe": "Milabrega's Robe",
  "Milabrega's Rod": "Milabrega's Rod",
  "Naj's Circlet": "Naj's Circlet",
  "Naj's Light Plate": "Naj's Light Plate",
  "Naj's Puzzler": "Naj's Puzzler",
  "Natalya's Mark": "Natalya's Mark",
  "Natalya's Shadow": "Natalya's Shadow",
  "Natalya's Soul": "Natalya's Soul",
  "Natalya's Totem": "Natalya's Totem",
  "Ondal's Almighty": "Ondal's Almighty",
  'Rite of Passage': 'Rite of Passage',
  "Sander's Paragon": "McAuley's Paragon",
  "Sander's Riprap": "McAuley's Riprap",
  "Sander's Superstition": "McAuley's Superstition",
  "Sander's Taboo": "McAuley's Taboo",
  "Sazabi's Cobalt Redeemer": "Sazabi's Cobalt Redeemer",
  "Sazabi's Ghost Liberator": "Sazabi's Ghost Liberator",
  "Sazabi's Mental Sheath": "Sazabi's Mental Sheath",
  "Sigon's Gage": "Sigon's Gage",
  "Sigon's Guard": "Sigon's Guard",
  "Sigon's Sabot": "Sigon's Sabot",
  "Sigon's Shelter": "Sigon's Shelter",
  "Sigon's Visor": "Sigon's Visor",
  "Sigon's Wrap": "Sigon's Wrap",
  "Taebaek's Glory": "Heaven's Taebaek",
  "Tal Rasha's Adjudication": "Tal Rasha's Adjudication",
  "Tal Rasha's Fine Spun Cloth": "Tal Rasha's Fire-Spun Cloth",
  "Tal Rasha's Guardianship": "Tal Rasha's Howling Wind",
  "Tal Rasha's Horadric Crest": "Tal Rasha's Horadric Crest",
  "Tal Rasha's Lidless Eye": "Tal Rasha's Lidless Eye",
  "Tancred's Crowbill": "Tancred's Crowbill",
  "Tancred's Hobnails": "Tancred's Hobnails",
  "Tancred's Skull": "Tancred's Skull",
  "Tancred's Spine": "Tancred's Spine",
  "Tancred's Weird": "Tancred's Weird",
  'Telling of Beads': 'Telling of Beads',
  "Trang-Oul's Claws": "Trang-Oul's Claws",
  "Trang-Oul's Girth": "Trang-Oul's Girth",
  "Trang-Oul's Guise": "Trang-Oul's Guise",
  "Trang-Oul's Scales": "Trang-Oul's Scales",
  "Trang-Oul's Wing": "Trang-Oul's Wing",
  "Vidala's Ambush": "Vidala's Ambush",
  "Vidala's Barb": "Vidala's Barb",
  "Vidala's Fetlock": "Vidala's Fetlock",
  "Vidala's Snare": "Vidala's Snare",
  "Whitstan's Guard": "Wihtstan's Guard",
  "Wilhelm's Pride": "Wilhelm's Pride",
}
