export const silospenMapping: { [itemName: string]: string } = {
  almanegra: 'Alma Negra',
  andarielsvisage: "Andariel's Visage",
  annihilus: 'Annihilus',
  arachnidmesh: 'Arachnid Mesh',
  ariocsneedle: "Arioc's Needle",
  arkainesvalor: "Arkaine's Valor",
  armofkingleoric: 'Arm of King Leoric',
  arreatsface: "Arreat's Face",
  astreonsironward: 'Ironward',
  athenaswrath: "Athena's Wrath",
  atmasscarab: "Atma's Scarab",
  atmaswail: "Atma's Wail",
  axeoffechmar: 'Fechmars Axe',
  azurewrath: 'Azurewrath',
  baezilsvortex: "Baezil's Vortex",
  baneash: 'Bane Ash',
  baranarsstar: "Baranar's Star",
  bartucscutthroat: 'Cutthroat1',
  bigginsbonnet: 'War Bonnet',
  bingszwang: 'Bing Sz Wang',
  blackhades: 'Black Hades',
  blackbogssharp: "Blackbog's Sharp",
  blackcleft: "Black Cleft",
  blackhandkey: 'Blackhand Key',
  blackhornsface: "Blackhorn's Face",
  blackleachblade: 'Blackleach Blade',
  blackoakshield: 'Blackoak Shield',
  blacktongue: 'Blacktongue',
  bladeofalibaba: 'Blade of Ali Baba',
  bladebone: 'Bladebone',
  bladebuckle: 'Bladebuckle',
  blastbark: 'Blastbark',
  blinkbatsform: 'Blinkbats Form',
  bloodcrescent: 'Blood Crescent',
  bloodravenscharge: "Bloodraven's Charge",
  bloodfist: 'Bloodfist',
  bloodletter: 'Bloodletter',
  bloodmoon: 'Bloodmoon',
  bloodrise: 'Bloodrise',
  bloodthief: 'Bloodthief',
  bloodtreestump: 'Bloodtree Stump',
  bonebreak: "Bone Break",
  boneflame: 'Boneflame',
  boneflesh: 'Boneflesh',
  bonehew: 'Bonehew',
  boneshade: 'Boneshade',
  boneslayerblade: 'Boneslayer Blade',
  bonesnap: 'Bonesob',
  brainhew: 'Brainhew',
  bulkathosweddingband: "Bul Katho's Wedding Band",
  burizadokyanon: 'Buriza-Do Kyanon',
  butcherspupil: "Butcher's Pupil",
  bverritkeep: 'Bverrit Keep',
  carinshard: 'Carin Shard',
  carrionwind: 'Carrion Wind',
  cerebusbite: 'Cerebus',
  chanceguards: 'Chance Guards',
  chromaticire: 'Chromatic Ire',
  cliffkiller: 'Cliffkiller',
  cloudcrack: 'Cloudcrack',
  coifofglory: 'Coif of Glory',
  coldkill: 'Coldkill',
  coldrupture: "Cold Rupture",
  coldsteeleye: 'Coldsteel Eye',
  corpsemourn: 'Corpsemourn',
  crackoftheheavens: 'Crack of the Heavens',
  craintevomir: 'Crainte Vomir',
  cranebeak: 'Cranebeak',
  crescentmoon: 'Crescent Moon',
  crowcaw: 'Crow Caw',
  crownofages: 'Crown of Ages',
  crownofthieves: 'Crown of Thieves',
  crushflange: 'Crushflange',
  culwenspoint: 'Culwens Point',
  darkclancrusher: 'Dark Clan Crusher',
  darkforcespawn: 'Darkforge Spawn',
  darkglow: 'Darkglow',
  darksighthelm: 'Darksight Helm',
  deathcleaver: 'Deathcleaver',
  deathsfathom: 'Fathom',
  deathsweb: "Deaths's Web",
  deathbit: 'Deathbit',
  deathspade: 'Deathspade',
  demonlimb: 'Demonlimb',
  demonmachine: 'Demon Machine',
  demonsarch: "Demon's Arch",
  demonhornsedge: "Demonhorn's Edge",
  dimoakshew: 'Dimoaks Hew',
  djinnslayer: 'Djinnslayer',
  doombringer: 'Doombringer',
  doomslinger: 'Doomspittle',
  draculsgrasp: "Dracul's Grasp",
  dragonscale: 'Dragonscale',
  durielsshell: "Duriel's Shell",
  duskdeep: 'Duskdeep',
  dwarfstar: 'Dwarf Star',
  eaglehorn: 'Eaglehorn',
  earthshifter: 'Earthshifter',
  earthshaker: 'Earthshaker',
  endlesshail: 'Endlesshail',
  eschutastemper: "Eschuta's temper",
  etherealedge: 'Ethereal Edge',
  executionersjustice: "Executioner's Justice",
  felloak: 'Felloak',
  firelizardstalons: "Firelizard's Talons",
  flamebellow: 'Flamebellow',
  flamerift: 'Flame Rift',
  fleshrender: 'Fleshrender',
  fleshripper: 'Fleshripper',
  frostburn: 'Frostburn',
  frostwind: 'Frostwind',
  gargoylesbite: "Gargoyle's Bite",
  gerkessanctuary: "Kerke's Sanctuary",
  gheedsfortune: "Gheed's Fortune",
  ghostflame: 'Ghostflame',
  ghoulhide: 'Ghoulhide',
  giantskull: 'Giantskull',
  gimmershred: 'Gimmershred',
  ginthersrift: "Ginther's Rift",
  gleamscythe: 'Gleamscythe',
  gloomstrap: 'Gloomstrap',
  goblintoe: 'Goblin Toe',
  goldskin: 'Goldskin',
  goldstrikearch: 'Godstrike Arch',
  goldwrap: 'Goldwrap',
  gorerider: 'Gorerider',
  gorefoot: 'Gorefoot',
  goreshovel: 'Goreshovel',
  gravenspine: 'Gravenspine',
  gravepalm: 'Gravepalm',
  greyform: 'Greyform',
  griffonseye: "Griffon's Eye",
  grimsburningdead: "Grim's Burning Dead",
  griswoldsedge: 'Griswolds Edge',
  guardianangel: 'Guardian Angel',
  guardiannaga: 'Guardian Naga',
  gull: 'Gull',
  gutsiphon: 'Gutsiphon',
  halaberdsreign: "Halaberd's Reign",
  handofblessedlight: 'Hand of Blessed Light',
  harlequincrest: 'Harlequin Crest',
  hawkmail: 'Hawkmail',
  headhuntersglory: "Headhunter's Glory",
  headstriker: 'Headstriker',
  heartcarver: 'Heart Carver',
  heavenslight: "Heaven's Light",
  heavenlygarb: 'Heavenly Garb',
  hellcast: 'Hellcast',
  hellclap: 'Hellclap',
  hellfiretorch: 'Hellfire Torch',
  hellmouth: 'Hellmouth',
  hellplague: 'Hellplague',
  hellrack: 'Hellrack',
  hellslayer: 'Hellslayer',
  heraldofzakarum: 'Herald of Zakarum',
  hexfire: 'Hexfire',
  highlordswrath: "Highlord's Wrath",
  homunculus: 'Homunculus',
  honesundan: 'Hone Sundan',
  horizonstornado: "Horizon's Tornado",
  hotspur: 'Hotspur',
  howltusk: 'Howltusk',
  humongous: 'The Humongous',
  husoldalevo: 'Husoldal Evo',
  iceblink: 'Iceblink',
  ichorsting: 'Ichorsting',
  infernostride: 'Infernostride',
  ironpelt: 'Ironpelt',
  ironstone: 'Ironstone',
  islestrike: 'Islestrike',
  jadetalon: 'Jadetalon',
  jalalsmane: "Jalal's Mane",
  kelpiesnare: 'Kelpie Snare',
  kinemilsawl: 'Kinemils Awl',
  kirasguardian: "Kira's Guardian",
  knellstriker: 'Knell Striker',
  kukoshakaku: 'Kuko Shakaku',
  lacerator: 'Lacerator',
  lanceguard: 'Lance Guard',
  lanceofyaggai: 'Lance of Yaggai',
  langerbriser: 'Langer Briser',
  lavagout: 'Lavagout',
  leadcrow: 'Leadcrow',
  lenymo: 'Lenyms Cord',
  leviathan: 'Leviathan',
  lidlesswall: 'Lidless Wall',
  lightsabre: 'Lightsabre',
  lycandersaim: "Lycander's Aim",
  lycandersflank: "Lycander's Flank",
  maelstrom: 'Maelstromwrath',
  magefist: 'Magefist',
  magewrath: 'Magewrath',
  manaldheal: 'Manald Heal',
  mangsongslesson: "Mang Song's Lesson",
  maraskaleidoscope: "Mara's Kaleidoscope",
  marrowwalk: 'Marrowwalk',
  medusasgaze: "Medusa's Gaze",
  messerschmidtsreaver: "Messerschmidt's Reaver",
  metalgrid: 'Metalgrid',
  moonfall: 'Moonfall',
  mosersblessedcircle: 'Mosers Blessed Circle',
  nagelring: 'Nagelring',
  naturespeace: "Nature's Peace",
  nightsmoke: 'Nightsmoke',
  nightwingsveil: "Nightwing's Veil",
  nokozanrelic: 'Nokozan Relic',
  nordstenderizer: "Nord's Tenderizer",
  nosferatuscoil: "Nosferatu's Coil",
  ondalswisdom: "Ondal's Wisdom",
  ormusrobes: "Ormus' Robes",
  peasantcrown: 'Peasent Crown',
  peltalunata: 'Pelta Lunata',
  pierretombalecouant: 'Pierre Tombale Couant',
  plaguebearer: 'Plague Bearer',
  pluckeye: 'Pluckeye',
  pompeiiswrath: "Pompe's Wrath",
  pusspitter: 'Pus Spiter',
  queheganswisdom: "Que-Hegan's Wisdon",
  radamentssphere: "Radimant's Sphere",
  rainbowfacetcolddeath: 'Rainbow Facet',
  rainbowfacetcoldlevelup: 'Rainbow Facet',
  rainbowfacetfiredeath: 'Rainbow Facet',
  rainbowfacetfirelevelup: 'Rainbow Facet',
  rainbowfacetlightningdeath: 'Rainbow Facet',
  rainbowfacetlightninglevelup: 'Rainbow Facet',
  rainbowfacetpoisondeath: 'Rainbow Facet',
  rainbowfacetpoisonlevelup: 'Rainbow Facet',
  rakescar: 'Rakescar',
  rattlecage: 'Rattlecage',
  ravenclaw: 'Rimeraven',
  ravenfrost: 'Raven Frost',
  ravenlore: 'Ravenlore',
  razorsedge: 'Razoredge',
  razorswitch: 'Razorswitch',
  razortail: 'Razortail',
  razortine: 'Razortine',
  ribcracker: 'Ribcracker',
  riphook: 'Riphook',
  ripsaw: 'Ripsaw',
  rixotskeen: 'Rixots Keen',
  rockfleece: 'Rockfleece',
  rockstopper: 'Rockstopper',
  roguesbow: 'Piercerib',
  runemaster: 'Runemaster',
  rusthandle: 'Rusthandle',
  rottingfissure: 'Rotting Fissure',
  sandstormtrek: 'Sandstorm Trek',
  saracenschance: "Saracen's Chance",
  schaefershammer: "Schaefer's Hammer",
  seraphshymn: "Seraph's Hymn",
  serpentlord: 'Serpent Lord',
  shadowdancer: 'Shadowdancer',
  shadowkiller: 'Shadowkiller',
  shadowfang: 'Shadowfang',
  shaftstop: 'Shaftstop',
  silksofthevictor: 'Victors Silk',
  silkweave: 'Silkweave',
  skewerofkrintiz: 'Krintizs Skewer',
  skinoftheflayedone: 'Skin of the Flayerd One',
  skinofthevipermagi: 'Skin of the Vipermagi',
  skullcollector: 'Skullcollector',
  skullsplitter: 'Mindrend',
  skulldersire: "Skullder's Ire",
  skystrike: 'Skystrike',
  snakecord: 'Snakecord',
  snowclash: 'Snowclash',
  souldrainer: 'Souldrain',
  soulharvest: 'Soul Harvest',
  soulfeasttine: 'Soulfeast Tine',
  soulflay: 'Soulflay',
  sparkingmail: 'Sparking Mail',
  spectralshard: 'Irices Shard',
  spellsteel: 'Spellsteel',
  spikethorn: 'Spike Thorn',
  spineripper: 'Spineripper',
  spireofhonor: 'Spire of Honor',
  spireoflazarus: 'Lazarus Spire',
  spiritforge: 'Spiritforge',
  spiritkeeper: 'Spiritkeeper',
  spiritward: 'Spirit Ward',
  stealskull: 'Stealskull',
  steelcarapace: 'Steel Carapice',
  steelpillar: 'Steelpillar',
  steelshade: 'Steelshade',
  steelclash: 'Steelclash',
  steeldriver: 'Steeldriver',
  steelgoad: 'Steelgoad',
  steelrend: 'Steelrend',
  stonecrusher: 'Stone Crusher',
  stoneraven: 'Stoneraven',
  stormchaser: 'Stormchaser',
  stormeye: 'Stormeye',
  stormguild: 'Stormguild',
  stormlash: 'Stormlash',
  stormrider: 'Stormrider',
  stormshield: 'Stormshield',
  stormspike: 'Stormspike',
  stormspire: 'Stormspire',
  stormstrike: 'Pullspite',
  stoutnail: 'Stoutnail',
  stringofears: 'String of Ears',
  suicidebranch: 'Suicide Branch',
  sureshrillfrost: 'Sureshrill Frost',
  swordbackhold: 'Swordback Hold',
  swordguard: 'Swordguard',
  tarnhelm: 'Tarnhelm',
  tearhaunch: 'Tearhaunch',
  templarsmight: "Templar's Might",
  theatlantean: 'The Atlantian',
  thebattlebranch: 'The Battlebranch',
  thecatseye: "The Cat's Eye",
  thecenturion: 'The Centurion',
  thechieftain: 'The Chieftan',
  thecraniumbasher: 'The Cranium Basher',
  thediggler: 'The Diggler',
  thedragonchang: 'The Dragon Chang',
  theeyeofetlich: 'The Eye of Etlich',
  thefaceofhorror: 'The Face of Horror',
  thefetidsprinkler: 'The Fetid Sprinkler',
  thegavelofpain: 'The Gavel of Pain',
  thegeneralstandoliga: 'The Generals Tan Do Li Ga',
  thegladiatorsbane: "The Gladiator's Bane",
  thegnasher: 'The Gnasher',
  thegrandfather: 'The Grandfather',
  thegrimreaper: 'The Grim Reaper',
  thehandofbroc: 'The Hand of Broc',
  theimpaler: 'The Impaler',
  theironjangbong: 'The Iron Jang Bong',
  thejadetando: 'The Jade Tan Do',
  themahimoakcurio: 'The Mahim-Oak Curio',
  themeatscraper: 'The Meat Scraper',
  theminotaur: 'The Minataur',
  theoculus: 'The Oculus',
  thepatriarch: 'The Patriarch',
  thereaperstoll: "The Reaper's Toll",
  theredeemer: 'The Reedeemer',
  therisingsun: 'The Rising Sun',
  thesalamander: 'The Salamander',
  thescalper: 'The Scalper',
  thespiritshroud: 'The Spirit Shroud',
  thestoneofjordan: 'The Stone of Jordan',
  thetannrgorerod: 'The Tannr Gorerod',
  thevilehusk: 'The Vile Husk',
  theward: 'The Ward',
  thundergodsvigor: "Thudergod's Vigor",
  thunderstroke: 'Thunderstroke',
  tiamatsrebuke: "Tiamat's Rebuke",
  titansrevenge: "Titan's Revenge",
  todesfaelleflamme: 'Todesfaelle Flamme',
  tombreaver: 'Tomb Reaver',
  toothrow: 'Toothrow',
  torchofiro: 'Iros Torch',
  treadsofcthon: 'Treads of Cthon',
  twitchthroe: 'Twitchthroe',
  tyraelsmight: "Tyrael's Might",
  umbraldisk: 'Umbral Disk',
  umeslament: 'Umes Lament',
  undeadcrown: 'Undead Crown',
  valkyriewing: 'Valkiry Wing',
  vampiregaze: 'Vampiregaze',
  veilofsteel: 'Veil of Steel',
  venomgrip: 'Venom Grip',
  venomward: 'Venomsward',
  verdungosheartycord: "Verdugo's Hearty Cord",
  viperfork: 'Viperfork',
  visceratuant: 'Visceratuant',
  walloftheeyeless: 'Wall of the Eyeless',
  wartraveler: 'Wartraveler',
  warlordstrust: "Warlord's Trust",
  warpspear: 'Warpspear',
  warshrike: 'Warshrike',
  waterwalk: 'Waterwalk',
  widowmaker: 'Widowmaker',
  windforce: 'Windforce',
  windhammer: 'Windhammer',
  wispprojector: 'Wisp',
  witchwildstring: 'Whichwild String',
  witherstring: 'Witherstring',
  wizardspike: 'Wizardspike',
  wizendraw: 'Wizendraw',
  woestave: 'Woestave',
  wolfhowl: 'Wolfhowl',
  wormskull: 'Wormskull',
  wraithflight: 'Wraithflight',
  zakarumshand: "Zakarum's Hand",
  aldursadvance: "Aldur's Advance",
  aldursdeception: "Aldur's Deception",
  aldursrhythm: "Aldur's Gauntlet",
  aldursstonygaze: "Aldur's Stony Gaze",
  angelichalo: 'Angelic Halo',
  angelicmantle: 'Angelic Mantle',
  angelicsickle: 'Angelic Sickle',
  angelicwings: 'Angelic Wings',
  arcannasdeathwand: "Arcanna's Deathwand",
  arcannasflesh: "Arcanna's Flesh",
  arcannashead: "Arcanna's Head",
  arcannassign: "Arcanna's Sign",
  arcticbinding: 'Arctic Binding',
  arcticfurs: 'Arctic Furs',
  arctichorn: 'Arctic Horn',
  arcticmitts: 'Arctic Mitts',
  berserkershatchet: "Berserker's Hatchet",
  berserkershauberk: "Berserker's Hauberk",
  berserkersheadgear: "Berserker's Headgear",
  bulkathossacredcharge: "Bul-Kathos' Sacred Charge",
  bulkathostribalguardian: "Bul-Kathos' Tribal Guardian",
  cathansmesh: "Cathan's Mesh",
  cathansrule: "Cathan's Rule",
  cathansseal: "Cathan's Seal",
  cathanssigil: "Cathan's Sigil",
  cathansvisage: "Cathan's Visage",
  civerbscudgel: "Civerb's Cudgel",
  civerbsicon: "Civerb's Icon",
  civerbsward: "Civerb's Ward",
  cleglawsclaw: "Cleglaw's Claw",
  cleglawspincers: "Cleglaw's Pincers",
  cleglawstooth: "Cleglaw's Tooth",
  cowkingshide: "Cow King's Hide",
  cowkingshooves: "Cow King's Hoofs",
  cowkingshorns: "Cow King's Horns",
  credendum: 'Credendum',
  dangoonsteaching: "Dangoon's Teaching",
  darkadherent: 'Spiritual Custodian',
  deathsguard: "Death's Guard",
  deathshand: "Death's Hand",
  deathstouch: "Death's Touch",
  griswoldsheart: "Griswold's Heart",
  griswoldshonor: "Griswold's Honor",
  griswoldsredemption: "Griswolds's Redemption",
  griswoldsvalor: "Griswold's Valor",
  guillaumesface: "Guillaume's Face",
  haemosusadamant: "Haemosu's Adament",
  hsarusironfist: "Hsarus' Iron Fist",
  hsarusironheel: "Hsarus' Iron Heel",
  hsarusironstay: "Hsarus' Iron Stay",
  hwaninsblessing: "Hwanin's Seal",
  hwaninsjustice: "Hwanin's Justice",
  hwaninsrefuge: "Hwanin's Refuge",
  hwaninssplendor: "Hwanin's Splendor",
  immortalkingsdetail: "Immortal King's Detail",
  immortalkingsforge: "Immortal King's Forge",
  immortalkingspillar: "Immortal King's Pillar",
  immortalkingssoulcage: "Immortal King's Soul Cage",
  immortalkingsstonecrusher: "Immortal King's Stone Crusher",
  immortalkingswill: "Immortal King's Will",
  infernalcranium: 'Infernal Cranium',
  infernalsign: 'Infernal Sign',
  infernaltorch: 'Infernal Torch',
  irathascoil: "Iratha's Coil",
  irathascollar: "Iratha's Collar",
  irathascord: "Iratha's Cord",
  irathascuff: "Iratha's Cuff",
  isenhartscase: "Isenhart's Case",
  isenhartshorns: "Isenhart's Horns",
  isenhartslightbrand: "Isenhart's Lightbrand",
  isenhartsparry: "Isenhart's Parry",
  layingofhands: 'Laying of Hands',
  mavinascaster: "M'avina's Caster",
  mavinasembrace: "M'avina's Embrace",
  mavinasicyclutch: "M'avina's Icy Clutch",
  mavinastenet: "M'avina's Tenet",
  mavinastruesight: "M'avina's True Sight",
  magnusskin: "Magnus' Skin",
  milabregasdiadem: "Milabrega's Diadem",
  milabregasorb: "Milabrega's Orb",
  milabregasrobe: "Milabrega's Robe",
  milabregasrod: "Milabrega's Rod",
  najscirclet: "Naj's Circlet",
  najslightplate: "Naj's Light Plate",
  najspuzzler: "Naj's Puzzler",
  natalyasmark: "Natalya's Mark",
  natalyasshadow: "Natalya's Shadow",
  natalyassoul: "Natalya's Soul",
  natalyastotem: "Natalya's Totem",
  ondalsalmighty: "Ondal's Almighty",
  riteofpassage: 'Rite of Passage',
  sandersparagon: "McAuley's Paragon",
  sandersriprap: "McAuley's Riprap",
  sanderssuperstition: "McAuley's Superstition",
  sanderstaboo: "McAuley's Taboo",
  sazabiscobaltredeemer: "Sazabi's Cobalt Redeemer",
  sazabisghostliberator: "Sazabi's Ghost Liberator",
  sazabismentalsheath: "Sazabi's Mental Sheath",
  sigonsgage: "Sigon's Gage",
  sigonsguard: "Sigon's Guard",
  sigonssabot: "Sigon's Sabot",
  sigonsshelter: "Sigon's Shelter",
  sigonsvisor: "Sigon's Visor",
  sigonswrap: "Sigon's Wrap",
  taebaeksglory: "Heaven's Taebaek",
  talrashasadjudication: "Tal Rasha's Adjudication",
  talrashasfinespuncloth: "Tal Rasha's Fire-Spun Cloth",
  talrashasguardianship: "Tal Rasha's Howling Wind",
  talrashashoradriccrest: "Tal Rasha's Horadric Crest",
  talrashaslidlesseye: "Tal Rasha's Lidless Eye",
  tancredscrowbill: "Tancred's Crowbill",
  tancredshobnails: "Tancred's Hobnails",
  tancredsskull: "Tancred's Skull",
  tancredsspine: "Tancred's Spine",
  tancredsweird: "Tancred's Weird",
  tellingofbeads: 'Telling of Beads',
  trangoulsclaws: "Trang-Oul's Claws",
  trangoulsgirth: "Trang-Oul's Girth",
  trangoulsguise: "Trang-Oul's Guise",
  trangoulsscales: "Trang-Oul's Scales",
  trangoulswing: "Trang-Oul's Wing",
  vidalasambush: "Vidala's Ambush",
  vidalasbarb: "Vidala's Barb",
  vidalasfetlock: "Vidala's Fetlock",
  vidalassnare: "Vidala's Snare",
  whitstansguard: "Wihtstan's Guard",
  wilhelmspride: "Wilhelm's Pride",
}
